@extends('layouts.admin')

@section('content')
        <!-- Breadcrumbs  -->
        <nav aria-label="breadcrumb" class="mb-2">
            <ol class="breadcrumb small">
                <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{ route('reports.index') }}">Report</a></li>
                <li class="breadcrumb-item active" aria-current="page">View</li>
            </ol>
        </nav>
<div class="container-fluid" id="reportPage">
    <div class="d-flex justify-content-between align-items-center flex-wrap mb-4">
        <div>
            <h5 class="text-muted">Report Date: {{ $report->start_date }} to {{ $report->end_date }}</h5>
            <p class="mb-0 text-muted">Generated by: {{ $report->user->name ?? 'Unknown' }}</p>
        </div>
        <div>
            <a href="#" id="downloadReport" style="background:rgb(3,62,129);color:white;padding:8px 16px;border:none;border-radius:6px;text-decoration:none;font-weight:600;">Download</a>
        </div>
    </div>

    <div class="row">
        <!-- Total Vehicles -->
        <div class="col-md-4 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Total vehicles</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $report->total_vehicles_range }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-car fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Log Updates Count -->
        <div class="col-md-4 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Log Changes made</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $logCount }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-edit fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Flagged Vehicles -->
        <div class="col-md-4 mb-4">
            <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Number of Flagged Vehicle</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ $report->flagged_vehicles_range }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-flag fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-4">
        <!-- Bar Chart -->
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-header">Bar Chart</div>
                <div class="card-body" style="height: 345px;">
                    <canvas id="reportBarChart" style="height: 100%; width: 100%;"></canvas>
                </div>
            </div>
        </div>

        <!-- Pie Chart -->
        <div class="col-md-6 mb-4">
            <div class="card shadow h-100">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-dark">Flagged vs Non-Flagged Vehicles</h6>
                </div>
                <div class="card-body">
                    @if(array_sum($pieChartData['data']) > 0)
                        <div style="position: relative; height: 300px;">
                            <canvas id="reportPieChart"></canvas>
                        </div>
                    @else
                        <p class="text-center text-muted mt-5">No vehicle data available in the selected range.</p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <!-- Area Chart -->
    <div class="row mb-4">
        <div class="col-12">
            <div class="card shadow">
                <div class="card-header">Vehicle Trend</div>
                <div class="card-body" style="height: 300px; overflow: visible;">
                    <canvas id="reportAreaChart" style="height: 100%; width: 100%;"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
    // Bar Chart
    const barCtx = document.getElementById('reportBarChart').getContext('2d');
    new Chart(barCtx, {
        type: 'bar',
        data: {
            labels: {!! json_encode($barChartData['labels']) !!},
            datasets: [{
                label: 'Number of Vehicles',
                data: {!! json_encode($barChartData['datasets'][0]['data']) !!},
                backgroundColor: '#48C9B0',
                borderColor: '#1ABC9C',
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            plugins: {
                legend: { display: true }
            },
            scales: {
                y: { beginAtZero: true, title: { display: true, text: 'Vehicles' }},
                x: { offset: false, title: { display: true, text: 'Hour' }}
            }
        }
    });

    // Pie Chart
    @if(array_sum($pieChartData['data']) > 0)
    const pieCtx = document.getElementById('reportPieChart').getContext('2d');
    new Chart(pieCtx, {
        type: 'doughnut',
        data: {
            labels: {!! json_encode($pieChartData['labels']) !!},
            datasets: [{
                data: {!! json_encode($pieChartData['data']) !!},
                backgroundColor: {!! json_encode($pieChartData['colors']) !!},
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            cutout: '60%',
            plugins: {
                legend: {
                    position: 'bottom',
                    labels: { boxWidth: 20, font: { size: 14 } }
                },
                tooltip: {
                    callbacks: {
                        label: function(context) {
                            const total = context.dataset.data.reduce((a, b) => a + b, 0);
                            const value = context.raw;
                            const percentage = ((value / total) * 100).toFixed(1);
                            return `${context.label}: ${value} (${percentage}%)`;
                        }
                    }
                }
            }
        },
        plugins: [{
            id: 'centerText',
            beforeDraw: function(chart) {
                const width = chart.width;
                const height = chart.height;
                const ctx = chart.ctx;
                const data = chart.data.datasets[0].data;
                const total = data.reduce((a, b) => a + b, 0);
                const nonFlagged = data[0];
                const flagged = data[1];
                const percentNonFlagged = ((nonFlagged / total) * 100).toFixed(1);
                const percentFlagged = ((flagged / total) * 100).toFixed(1);

                ctx.save();
                ctx.font = 'bold 14px Arial';
                ctx.fillStyle = '#333';
                ctx.textAlign = 'center';
                ctx.textBaseline = 'middle';

                const centerX = width / 2;
                const centerY = height / 2;

                ctx.fillText(`Flagged: ${percentFlagged}%`, centerX, centerY - 30);
                ctx.fillText(`Non-Flagged: ${percentNonFlagged}%`, centerX, centerY + 0);
                ctx.restore();
            }
        }]
    });
    @endif

    // Area Chart
    const areaCtx = document.getElementById('reportAreaChart').getContext('2d');
    new Chart(areaCtx, {
        type: 'line',
        data: {
            labels: {!! json_encode($areaChartData['labels']) !!},
            datasets: [{
                label: 'Number of Vehicles',
                data: {!! json_encode($areaChartData['datasets'][0]['data']) !!},
                backgroundColor: 'rgba(55, 158, 227, 0.62)',
                borderColor: '#5DADE2',
                pointBackgroundColor: '#5DADE2',
                tension: 0.4,
                fill: true
            }]
        },
        options: {
            responsive: true,
            plugins: { legend: { display: true } },
            scales: {
                y: { beginAtZero: true, title: { display: true, text: 'Vehicles' }},
                x: { offset: false, title: { display: true, text: 'Hour' }}
            }
        }
    });
</script>
@endpush
