@extends('layouts.admin')
@section('content')

<div class="container-fluid" id="reportPage">
    <!-- Header -->
    <div class="row mb-3 align-items-center">
        <div class="col-12 d-flex justify-content-between align-items-start flex-wrap px-2">
            <div style="font-size:1.08rem; color:#868ea1;">
                <div class="mb-1">
                    <i class="fas fa-calendar-alt"></i>
                    <span style="font-weight: 500;">Date Range:</span>
                    {{ $report->start_date }} to {{ $report->end_date }}
                </div>
                <div>
                    <i class="fas fa-user"></i>
                    <span style="font-weight: 500;">Generated by:</span>
                    {{ $report->user->name ?? 'Unknown' }}
                </div>
            </div>
            <div>
                <button id="downloadReport" class="btn btn-primary" style="border-radius: 10px; font-weight: 600;">
                    <i class="fas fa-download"></i> Download Report
                </button>
            </div>
        </div>
    </div>

    <!-- Dashboard Cards -->
    <div class="row g-4 mb-4 justify-content-center">
        <div class="col-12 col-sm-6 col-md-4 col-lg-2">
            <div class="card dashboard-card h-100">
                <div class="card-body text-center">
                    <span class="icon-outline text-warning mb-2"><i class="fas fa-edit"></i></span>
                    <div class="mt-2 text-xs fw-bold text-warning text-uppercase mb-2 stat-title"><b>Log</b><br><b> Changes</b></div>
                    <div class="fs-4 fw-bold text-dark stat-value"><b>{{ $logCount }}</b></div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-2">
            <div class="card dashboard-card h-100">
                <div class="card-body text-center">
                    <span class="icon-outline text-danger mb-2"><i class="fas fa-flag"></i></span>
                    <div class="mt-2 text-xs fw-bold text-danger text-uppercase mb-2 stat-title"><b>Flagged Vehicles</b></div>
                    <div class="fs-4 fw-bold text-dark stat-value"><b>{{ $report->flagged_vehicles_range }}</b></div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-2">
            <div class="card dashboard-card h-100">
                <div class="card-body text-center">
                    <span class="icon-outline text-primary mb-2"><i class="fas fa-sign-in-alt"></i></span>
                    <div class="mt-2 text-xs fw-bold text-primary text-uppercase mb-2 stat-title"><b>Total Vehicles Entered </b></div>
                    <div class="fs-4 fw-bold text-dark stat-value"><b>{{ $vehiclesEntered }}</b></div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-2">
            <div class="card dashboard-card h-100">
                <div class="card-body text-center">
                    <span class="icon-outline text-success mb-2"><i class="fas fa-sign-out-alt"></i></span>
                    <div class="mt-2 text-xs fw-bold text-success text-uppercase mb-2 stat-title"><b>Total Vehicles Exited</b></div>
                    <div class="fs-4 fw-bold text-dark stat-value"><b>{{ $vehiclesExited }}</b></div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4 col-lg-2">
            <div class="card dashboard-card h-100">
                <div class="card-body text-center">
                    <span class="icon-outline text-info mb-2"><i class="fas fa-parking"></i></span>
                    <div class="mt-2 text-xs fw-bold text-info text-uppercase mb-2 stat-title"><b>Vehicles still in Campus</b></div>
                    <div class="fs-4 fw-bold text-dark stat-value"><b>{{ $stillInCampus }}</b></div>
                </div>
            </div>
        </div>
    </div>

    <!-- Charts Row -->
    <div class="row g-4 mb-4">
        <div class="col-12 col-xl-6 mb-4">
            <div class="card shadow chart-card h-100">
                <div class="card-header bg-white border-0 pb-0">
                    <h6 class="mb-0" style="color:#155e75;font-weight:700;">Entry vs Exit</h6>
                </div>
                <div class="card-body p-2 d-flex align-items-center justify-content-center" style="height:350px;">
                    <canvas id="reportBarChart" width="360" height="300"></canvas>
                </div>
            </div>
        </div>
        <div class="col-12 col-xl-6 mb-4">
            <div class="card shadow chart-card h-100">
                <div class="card-header bg-white border-0 pb-0">
                    <h6 class="mb-0" style="color:#155e75;font-weight:700;">Flagged vs Non-Flagged Vehicles</h6>
                </div>
                <div class="card-body px-4 py-4" style="height:400px;">
                    @if(array_sum($pieChartData['data']) > 0)
                    <div style="display: flex; align-items: center; justify-content: flex-start; height: 100%; width: 100%; min-width: 420px;">
                        <div style="width:300px; height:300px; margin-right:50px; flex-shrink:0;">
                            <canvas id="reportPieChart"></canvas>
                        </div>
                        <div style="margin-left:12px; min-width:200px;">
                            <div class="d-flex align-items-center mb-3">
                                <div style="width:30px; height:16px; background:#4caf50; border-radius:4px; margin-right:3px;"></div>
                                <span style="font-size:1rem; color:#555;">Non-Flagged Vehicles</span>
                            </div>
                            <div class="d-flex align-items-center">
                                <div style="width:30px; height:16px; background:#f44336; border-radius:4px; margin-right:3px;"></div>
                                <span style="font-size:1rem; color:#555;">Flagged Vehicles</span>
                            </div>
                        </div>
                    </div>
                    @else
                        <p class="text-center text-muted mt-5">No vehicle data available in the selected range.</p>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-4 g-4 align-items-stretch">
        <div class="col-12 col-xl-8">
            <div class="card shadow chart-card h-100">
                <div class="card-header bg-white border-0 pb-0">
                    <h6 class="mb-0" style="color:#155e75;font-weight:700;">Vehicle Trend</h6>
                </div>
                <div class="card-body p-3" style="height:370px;">
                    <canvas id="reportAreaChart"></canvas>
                </div>
            </div>
        </div>
        <div class="col-12 col-xl-4">
            <div class="card shadow-sm h-100 d-flex flex-column justify-content-center" style="border-radius: 20px;">
                <div class="pt-4 pb-0 px-4">
                    <h5 style="color:#175ad3; font-weight:700; margin-bottom:0;">Key Insights</h5>
                </div>
                <div class="card-body text-dark d-flex flex-column justify-content-center" style="width:100%; height:100%; padding: 1.4rem 2rem 1.2rem 2rem;">
                    <ul style="font-size:1.07rem; padding-left:0; list-style-position:inside; width:100%; margin-bottom:1.2rem;">
                        <li><b>Peak Hour: <span style="color:#ed3c50">{{ $peakHour }}</span></b><br><b style="padding: 1rem">(Number of vehicles: {{ $peakHourCount }})</b></li>
                        <li><b>Total Vehicles in Range:</b> {{ $report->total_vehicles_range ?? 0 }}</li>
                        <li><b>Flagged Vehicles:</b> {{ $report->flagged_vehicles_range ?? 0 }} ({{ $report->total_vehicles_range > 0 ? round(($report->flagged_vehicles_range / $report->total_vehicles_range) * 100, 1) : 0 }}%)</li>
                        <li><b>Current Vehicles in Campus:</b> {{ $stillInCampus ?? 0 }}</li>
                        <li><b>Entry/Exit Activity:</b> {{ $vehiclesEntered ?? 0 }} entered, {{ $vehiclesExited ?? 0 }} exited</li>
                    </ul>
                    <p class="mt-2 mb-0" style="font-size:0.97rem; width:100%;">
                        <i class="fas fa-info-circle"></i>
                        The busiest period recorded was at <b style="color:#ed3c50">{{ $peakHour ?? '-' }}</b> with {{ $peakHourCount ?? 0 }} vehicles.
                        Flagged vehicles made up {{ $report->total_vehicles_range > 0 ? round(($report->flagged_vehicles_range / $report->total_vehicles_range) * 100, 1) : 0 }}% of all activity.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <!-- Table: Log Changes in Range -->
    
    <h4 class="mt-5 mb-3 text-primary" style="font-weight:700;">Log Changes</h4>
    <div class="card shadow mb-4">
    <div class="card-body table-responsive p-3">
        <table class="table table-bordered table-striped align-middle">
            <thead style="background:rgb(3,62,129);color:#fff;">
                    <tr>
                        <th>Date & Time</th>
                        <th>Vehicle Plate</th>
                        <th>Action</th>
                        <th>Change Description</th>
                        <th>Changed By</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($logChanges as $log)
                        <tr>
                            <td>{{ $log->created_at }}</td>
                            <td>{{ $log->plate->plate_text ?? '-' }}</td>
                            <td>{{ ucfirst($log->action) }}</td>
                            <td>{{ $log->message }}</td>
                            <td>{{ $log->user->name ?? 'Unknown' }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="text-center text-muted">No log changes in this range.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>


    <!-- Flagged Vehicles Table -->
     <h4 class="mt-5 mb-3 text-primary" style="font-weight:700;">Flagged Vehicles</h4>
    <div class="card shadow mb-4">
    <div class="card-body table-responsive p-3">
        <table class="table table-bordered table-striped align-middle">
            <thead style="background:rgb(3,62,129);color:#fff;">
                    <tr>
                        <th>No</th>
                        <th>Plate Number</th>
                        <th>Entry Time</th>
                        <th>Exit Time</th>
                        <th>Registered</th>
                        <th>Reason</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($flaggedVehicles as $i => $plate)
                        <tr>
                            <td>{{ $i+1 }}</td>
                            <td>{{ $plate->plate_text }}</td>
                            <td>{{ $plate->entry_time }}</td>
                            <td>{{ $plate->exit_time ?? '-' }}</td>
                            <td>
                                @if ($plate->registeredVehicle)
                                    <i class="fas fa-check-circle text-success"></i>
                                @else
                                    <i class="fas fa-times-circle text-danger"></i>
                                @endif
                            </td>
                            <td>{{ $plate->reason ?? '-' }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="text-muted">No flagged vehicles in this range.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <!-- Table: Total Vehicles Entered in Range -->
    <h4 class="mt-5 mb-3 text-primary" style="font-weight:700;">Total Vehicles Entered</h4>
    <div class="card shadow mb-4">
        <div class="card-body table-responsive p-3">
            <table class="table table-bordered table-striped align-middle">
                <thead style="background:rgb(3,62,129);color:#fff;">
                    <tr>
                        <th>No</th>
                        <th>Entry Time</th>
                        <th>License Plate</th>
                        <th>Registered</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($vehiclesInRange as $i => $vehicle)
                        <tr>
                            <td>{{ $i+1 }}</td>
                            <td>{{ $vehicle->entry_time }}</td>
                            <td>{{ $vehicle->plate_text }}</td>
                            <td>
                                @if ($vehicle->registeredVehicle)
                                    <i class="fas fa-check-circle text-success"></i>
                                @else
                                    <i class="fas fa-times-circle text-danger"></i>
                                @endif
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="text-center text-muted">No vehicles entered in this range.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <!-- Table: Total Vehicles Exited in Range -->
    <h4 class="mt-5 mb-3 text-primary" style="font-weight:700;">Total Vehicles Exited </h4>
    <div class="card shadow mb-4">
        <div class="card-body table-responsive p-3">
            <table class="table table-bordered table-striped align-middle">
                <thead style="background:rgb(3,62,129);color:#fff;">
                    <tr>
                        <th>No</th>
                        <th>Exit Time</th>
                        <th>License Plate</th>
                        <th>Registered</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($vehiclesExitedInRange as $i => $vehicle)
                        <tr>
                            <td>{{ $i+1 }}</td>
                            <td>{{ $vehicle->exit_time }}</td>
                            <td>{{ $vehicle->plate_text }}</td>
                            <td>
                                @if ($vehicle->registeredVehicle)
                                    <i class="fas fa-check-circle text-success"></i>
                                @else
                                    <i class="fas fa-times-circle text-danger"></i>
                                @endif
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="6" class="text-center text-muted">No vehicles exited in this range.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>

    <!-- Table: Vehicles Still in Campus (in Range) -->
    <h4 class="mt-5 mb-3 text-primary" style="font-weight:700;">Vehicles Still in Campus </h4>
    <div class="card shadow mb-4">
        <div class="card-body table-responsive p-3">
            <table class="table table-bordered table-striped align-middle">
                <thead style="background:rgb(3,62,129);color:#fff;">
                    <tr>
                        <th>No</th>
                        <th>Entry Time</th>
                        <th>License Plate</th>
                        <th>Registered</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($vehiclesStillInCampus as $i => $vehicle)
                        <tr>
                            <td>{{ $i+1 }}</td>
                            <td>{{ $vehicle->entry_time }}</td>
                            <td>{{ $vehicle->plate_text }}</td>
                            <td>
                                @if ($vehicle->registeredVehicle)
                                    <i class="fas fa-check-circle text-success"></i>
                                @else
                                    <i class="fas fa-times-circle text-danger"></i>
                                @endif
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="text-center text-muted">No vehicles still in campus in this range.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>





<!-- Styling -->
<style>
    .table tbody td, .table tbody th {
        color: #222 !important;
    }
    .table-striped > tbody > tr:nth-of-type(odd) > * {
        color: #222 !important;
    }
    
    .dashboard-card {
        box-shadow: 0 8px 24px rgba(8, 79, 160, 0.3);
        border-radius: 24px;
        background: #fff;
    }
    .icon-outline {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        width: 44px;
        height: 44px;
        border-radius: 50%;
        border: 2.5px solid #15c0d5;
        font-size: 1.6rem;
        margin-bottom: 5px;
    }
    .icon-outline.text-info { border-color: #15c0d5; color: #15c0d5;}
    .icon-outline.text-primary { border-color: #175ad3; color: #175ad3;}
    .icon-outline.text-danger { border-color: #ed3c50; color: #ed3c50;}
    .icon-outline.text-success { border-color: #36d399; color: #36d399;}
    .icon-outline.text-warning { border-color: #f6c957; color: #f6c957;}
    .stat-title {
        font-size: 15px;
        font-weight: 400;
        letter-spacing: .02em;
        margin-bottom: 0.16rem;
        text-transform: uppercase;
    }
    .stat-value {
        color: #424242;
        margin-top: 0.1rem;
    }
    .table thead th {
        vertical-align: middle;
        text-align: center;
    }
    .badge {
        font-size: 1rem;
        font-weight: 600;
        padding: .4em .8em;
    }
</style>

@endsection

@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<script>
    // BAR CHART
    const barCtx = document.getElementById('reportBarChart').getContext('2d');
    new Chart(barCtx, {
        type: 'bar',
        data: {
            labels: {!! json_encode($barChartData['labels']) !!},
            datasets: {!! json_encode($barChartData['datasets']) !!}
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: { legend: { display: true, position: 'top' } },
            scales: {
                y: { beginAtZero: true, title: { display: true, text: 'Vehicles' }},
                x: { title: { display: true, text: 'Hour' }, ticks: { autoSkip: false, maxRotation: 45 } }
            }
        }
    });

    // DONUT CHART
    @if(array_sum($pieChartData['data']) > 0)
    const donutCenterText = {
        id: 'centerText',
        afterDraw(chart) {
            const {ctx, chartArea: {width, height}} = chart;
            const data = chart.data.datasets[0].data;
            const total = data.reduce((a, b) => a + b, 0);
            const nonFlagged = data[0];
            const flagged = data[1];
            const percentNonFlagged = ((nonFlagged / total) * 100).toFixed(1);
            const percentFlagged = ((flagged / total) * 100).toFixed(1);

            ctx.save();
            ctx.font = 'bold 16px Inter, Arial, sans-serif';
            ctx.fillStyle = '#45435B';
            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';
            ctx.fillText(`Flagged: ${percentFlagged}%`, width / 2, height / 2 - 12);
            ctx.font = 'bold 16px Inter, Arial, sans-serif';
            ctx.fillStyle = '#45435B';
            ctx.fillText(`Non-Flagged: ${percentNonFlagged}%`, width / 2, height / 2 + 10);
            ctx.restore();
        }
    };

    const pieCtx = document.getElementById('reportPieChart').getContext('2d');
    new Chart(pieCtx, {
        type: 'doughnut',
        data: {
            labels: {!! json_encode($pieChartData['labels']) !!},
            datasets: [{
                data: {!! json_encode($pieChartData['data']) !!},
                backgroundColor: {!! json_encode($pieChartData['colors']) !!},
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            cutout: '68%',
            plugins: {
                legend: {
                    display: false,
                },
                tooltip: {
                    callbacks: {
                        label: function(context) {
                            const total = context.dataset.data.reduce((a, b) => a + b, 0);
                            const value = context.raw;
                            const percentage = ((value / total) * 100).toFixed(1);
                            return `${context.label}: ${value} (${percentage}%)`;
                        }
                    }
                }
            }
        },
        plugins: [donutCenterText]
    });
    @endif

    // AREA CHART
    const areaCtx = document.getElementById('reportAreaChart').getContext('2d');
    let entriesGradient = areaCtx.createLinearGradient(0, 0, 0, 370);
    entriesGradient.addColorStop(0, "rgba(99,102,241,0.23)");
    entriesGradient.addColorStop(1, "rgba(99,102,241,0.02)");

    let exitsGradient = areaCtx.createLinearGradient(0, 0, 0, 370);
    exitsGradient.addColorStop(0, "rgba(236,72,153,0.21)");
    exitsGradient.addColorStop(1, "rgba(236,72,153,0.01)");

    new Chart(areaCtx, {
        type: 'line',
        data: {
            labels: {!! json_encode($areaChartData['labels']) !!},
            datasets: [
                {
                    label: 'Entry',
                    data: {!! json_encode($areaChartData['datasets'][0]['data']) !!},
                    borderColor: '#4F8DFD',
                    backgroundColor: entriesGradient,
                    pointBackgroundColor: '#3969d9',
                    pointRadius: 4,
                    fill: true,
                    tension: 0.41,
                    borderWidth: 2
                },
                {
                    label: 'Exits',
                    data: {!! json_encode($areaChartData['datasets'][1]['data']) !!},
                    borderColor: '#f04b90',
                    backgroundColor: exitsGradient,
                    pointBackgroundColor: '#f04b90',
                    pointRadius: 4,
                    fill: true,
                    tension: 0.41,
                    borderWidth: 2
                }
            ]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: {
                    display: true,
                    position: 'top',
                    labels: { font: { size: 15, family: 'Inter' } }
                }
            },
            scales: {
                y: { beginAtZero: true, title: { display: true, text: 'Vehicles' }},
                x: { offset: false, title: { display: true, text: 'Hour' }}
            }
        }
    });

    // Download as PDF
    document.getElementById('downloadReport').addEventListener('click', function(e) {
        e.preventDefault();
        const element = document.getElementById('reportPage');
        const opt = {
            margin: 0,
            filename: 'Report.pdf',
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas:  { scale: 2, useCORS: true },
            jsPDF: { unit: 'px', format: [1200, 1700], orientation: 'landscape' }
        };
        html2pdf().set(opt).from(element).save();
    });
</script>
@endpush
