<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    use HasFactory;

    protected $fillable = [
        'date_range',        // e.g., "2025-05-01 to 2025-05-10"
        'generated_by',      // user_id (admin)
        'timestamp_created', // datetime the report was made
    ];

    // A report is generated by a user
    public function user()
    {
        return $this->belongsTo(User::class, 'generated_by');
    }
}
