<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    use HasFactory;

     protected $fillable = [
        'start_date',
        'end_date',
        'total_vehicles_range',
        'total_vehicles_today',
        'flagged_vehicles_range',
        'flagged_vehicles_today',
        'generated_by',
        'timestamp_created'
    ];

    // A report is generated by a user
    public function user()
    {
        return $this->belongsTo(User::class, 'generated_by');
    }
}
